{"TimeStamp":"2018-11-01T13:39:34.0953612+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Engines.EngineDataIntegrity.EngineDataIntegrity.IsDataIntegrityIssueExist() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Engines\\EngineDataIntegrity\\EngineDataIntegrity.cs:line 80]Value cannot be null.\r\nParameter name: source","Date":"18/11/01 01:39:34 PM"}
{"TimeStamp":"2018-11-01T14:12:06.3381322+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/11/01 02:12:06 PM"}
{"TimeStamp":"2018-11-01T14:12:10.1721306+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/11/01 02:12:10 PM"}
{"TimeStamp":"2018-11-01T14:12:24.5682241+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Engines.EngineDataIntegrity.EngineDataIntegrity.IsDataIntegrityIssueExist() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Engines\\EngineDataIntegrity\\EngineDataIntegrity.cs:line 80]Value cannot be null.\r\nParameter name: source","Date":"18/11/01 02:12:24 PM"}
{"TimeStamp":"2018-11-01T14:49:15.968301+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/11/01 02:49:15 PM"}
{"TimeStamp":"2018-11-01T14:49:18.8903741+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/11/01 02:49:18 PM"}
{"TimeStamp":"2018-11-01T14:49:41.6074726+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Engines.EngineDataIntegrity.EngineDataIntegrity.IsDataIntegrityIssueExist() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Engines\\EngineDataIntegrity\\EngineDataIntegrity.cs:line 80]Value cannot be null.\r\nParameter name: source","Date":"18/11/01 02:49:41 PM"}
{"TimeStamp":"2018-12-10T12:10:51.5287455+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/10 12:10:51 PM"}
{"TimeStamp":"2018-12-10T12:10:55.4852629+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/10 12:10:55 PM"}
{"TimeStamp":"2018-12-10T12:11:53.1657782+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/10 12:11:53 PM"}
{"TimeStamp":"2018-12-10T12:11:55.132235+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/10 12:11:55 PM"}
{"TimeStamp":"2018-12-10T12:11:55.1422347+01:00","MessageType":"INFO","Message":"Monthly Operation Summary Successfully Executed","Date":"18/12/10 12:11:55 PM"}
{"TimeStamp":"2018-12-10T12:12:13.4652233+01:00","MessageType":"ERROR>>System","Message":"[System.Net.Mail.SmtpException: Failure sending mail. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   at PatientDataAdministration.Core.Messaging.SendMail(String destination, String ccDestination, String bccDestination, String messageHeading, String message, String attachments) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Core\\Messaging.cs:line 91]Failure sending mail.","Date":"18/12/10 12:12:13 PM"}
{"TimeStamp":"2018-12-10T12:12:13.4772241+01:00","MessageType":"ERROR>>System","Message":"[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)]Unable to connect to the remote server","Date":"18/12/10 12:12:13 PM"}
{"TimeStamp":"2018-12-10T12:12:15.9702235+01:00","MessageType":"ERROR>>System","Message":"[System.Net.Mail.SmtpException: Failure sending mail. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   at PatientDataAdministration.Core.Messaging.SendMail(String destination, String ccDestination, String bccDestination, String messageHeading, String message, String attachments) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Core\\Messaging.cs:line 91]Failure sending mail.","Date":"18/12/10 12:12:15 PM"}
{"TimeStamp":"2018-12-10T12:12:15.9822216+01:00","MessageType":"ERROR>>System","Message":"[System.Net.Mail.SmtpException: Failure sending mail. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   at PatientDataAdministration.Core.Messaging.SendMail(String destination, String ccDestination, String bccDestination, String messageHeading, String message, String attachments) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Core\\Messaging.cs:line 91]Failure sending mail.","Date":"18/12/10 12:12:15 PM"}
{"TimeStamp":"2018-12-10T12:12:15.9942237+01:00","MessageType":"ERROR>>System","Message":"[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)]Unable to connect to the remote server","Date":"18/12/10 12:12:15 PM"}
{"TimeStamp":"2018-12-10T12:12:16.0052228+01:00","MessageType":"ERROR>>System","Message":"[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.185.7.123:25\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)\r\n   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)\r\n   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)\r\n   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)\r\n   at System.Net.Mail.SmtpClient.GetConnection()\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)]Unable to connect to the remote server","Date":"18/12/10 12:12:16 PM"}
{"TimeStamp":"2018-12-10T12:12:16.0152223+01:00","MessageType":"INFO","Message":"Monthly Operation Summary Successfully Executed","Date":"18/12/10 12:12:16 PM"}
{"TimeStamp":"2018-12-10T12:12:16.0272217+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/10 12:12:16 PM"}
{"TimeStamp":"2018-12-10T12:12:51.5418839+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/10 12:12:51 PM"}
{"TimeStamp":"2018-12-10T12:12:51.8638816+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/10 12:12:51 PM"}
{"TimeStamp":"2018-12-10T12:12:56.8024751+01:00","MessageType":"INFO","Message":"Sync Compliance Notification Successfully Executed","Date":"18/12/10 12:12:56 PM"}
{"TimeStamp":"2018-12-13T18:55:15.0164734+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/13 06:55:15 PM"}
{"TimeStamp":"2018-12-13T18:55:18.6212769+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/13 06:55:18 PM"}
{"TimeStamp":"2018-12-13T18:56:03.4477737+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Engines.EngineDataIntegrity.EngineDataIntegrity.IsDataIntegrityIssueExist() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Engines\\EngineDataIntegrity\\EngineDataIntegrity.cs:line 80]Value cannot be null.\r\nParameter name: source","Date":"18/12/13 06:56:03 PM"}
{"TimeStamp":"2018-12-13T18:56:15.410792+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/13 06:56:15 PM"}
{"TimeStamp":"2018-12-13T18:56:15.9917915+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/13 06:56:15 PM"}
{"TimeStamp":"2018-12-13T18:56:19.6737902+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/13 06:56:19 PM"}
{"TimeStamp":"2018-12-13T18:57:41.8760308+01:00","MessageType":"INFO","Message":"Sync Compliance Notification Successfully Executed","Date":"18/12/13 06:57:41 PM"}
{"TimeStamp":"2018-12-13T19:00:15.0685834+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/13 07:00:15 PM"}
{"TimeStamp":"2018-12-13T19:00:15.2325844+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/13 07:00:15 PM"}
{"TimeStamp":"2018-12-13T19:02:53.0609697+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/13 07:02:53 PM"}
{"TimeStamp":"2018-12-13T19:02:56.1109714+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/13 07:02:56 PM"}
{"TimeStamp":"2018-12-13T19:09:02.6837935+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/13 07:09:02 PM"}
{"TimeStamp":"2018-12-13T19:09:05.2967952+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/13 07:09:05 PM"}
{"TimeStamp":"2018-12-13T19:15:13.3118096+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/13 07:15:13 PM"}
{"TimeStamp":"2018-12-13T19:15:15.6278319+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/13 07:15:15 PM"}
{"TimeStamp":"2018-12-13T19:15:53.605211+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Engines.EngineDataIntegrity.EngineDataIntegrity.IsDataIntegrityIssueExist() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Engines\\EngineDataIntegrity\\EngineDataIntegrity.cs:line 80]Value cannot be null.\r\nParameter name: source","Date":"18/12/13 07:15:53 PM"}
{"TimeStamp":"2018-12-20T10:02:20.6715709+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 10:02:20 AM"}
{"TimeStamp":"2018-12-20T10:02:37.0264075+01:00","MessageType":"ERROR>>EntityFramework","Message":"[System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified\r\n   --- End of inner exception stack trace ---\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCr","Date":"18/12/20 10:02:37 AM"}
{"TimeStamp":"2018-12-20T10:02:37.0353856+01:00","MessageType":"ERROR>>.Net SqlClient Data Provider","Message":"[System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n ","Date":"18/12/20 10:02:37 AM"}
{"TimeStamp":"2018-12-20T10:02:37.145767+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 10:02:37 AM"}
{"TimeStamp":"2018-12-20T10:02:41.4357276+01:00","MessageType":"ERROR>>EntityFramework","Message":"[System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The system cannot find the file specified\r\n   --- End of inner exception stack trace ---\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection","Date":"18/12/20 10:02:41 AM"}
{"TimeStamp":"2018-12-20T10:02:41.4437253+01:00","MessageType":"ERROR>>.Net SqlClient Data Provider","Message":"[System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)\r\n   at System.Data.Entity.Infrastructure.Interception.InternalDispat","Date":"18/12/20 10:02:41 AM"}
{"TimeStamp":"2018-12-20T10:03:34.8323052+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/20 10:03:34 AM"}
{"TimeStamp":"2018-12-20T10:03:38.1587958+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/20 10:03:38 AM"}
{"TimeStamp":"2018-12-20T10:03:38.3937928+01:00","MessageType":"ERROR>>PatientDataAdministration.Web","Message":"[System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.PullNew(String encodedListOfAvailablePepId, Int32 siteId) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 120]Object reference not set to an instance of an object.","Date":"18/12/20 10:03:38 AM"}
{"TimeStamp":"2018-12-20T10:03:41.9333985+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/20 10:03:41 AM"}
{"TimeStamp":"2018-12-20T10:04:01.9624449+01:00","MessageType":"ERROR>>System.Core","Message":"[System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at PatientDataAdministration.Web.Areas.ServerCommunication.Controllers.IndicatorsController.<>c__DisplayClass7_0.<GetSiteDistro>b__2(IGrouping`2 grp) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ServerCommunication\\Controllers\\IndicatorsController.cs:line 385\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at PatientDataAdministration.Web.Areas.ServerCommunication.Controllers.IndicatorsController.GetSiteDistro() in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ServerCommunication\\Controllers\\IndicatorsController.cs:line 383]Value cannot be null.\r\nParameter name: source","Date":"18/12/20 10:04:01 AM"}
{"TimeStamp":"2018-12-20T10:04:04.560975+01:00","MessageType":"ERROR>>PatientDataAdministration.Web","Message":"[System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.PullNew(String encodedListOfAvailablePepId, Int32 siteId) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 120]Object reference not set to an instance of an object.","Date":"18/12/20 10:04:04 AM"}
{"TimeStamp":"2018-12-20T10:04:25.1429439+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 10:04:25 AM"}
{"TimeStamp":"2018-12-20T10:04:30.9503808+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 10:04:30 AM"}
{"TimeStamp":"2018-12-20T10:05:12.5592936+01:00","MessageType":"ERROR>>PatientDataAdministration.Web","Message":"[System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.PullNew(String encodedListOfAvailablePepId, Int32 siteId) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 120]Object reference not set to an instance of an object.","Date":"18/12/20 10:05:12 AM"}
{"TimeStamp":"2018-12-20T10:05:55.4426005+01:00","MessageType":"ERROR>>PatientDataAdministration.Web","Message":"[System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.PullNew(String encodedListOfAvailablePepId, Int32 siteId) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 120]Object reference not set to an instance of an object.","Date":"18/12/20 10:05:55 AM"}
{"TimeStamp":"2018-12-20T10:05:55.8456001+01:00","MessageType":"INFO","Message":"No Pending Appointments at the moment","Date":"18/12/20 10:05:55 AM"}
{"TimeStamp":"2018-12-20T10:05:56.4585988+01:00","MessageType":"INFO","Message":"Daily Operation Summary Successfully Executed","Date":"18/12/20 10:05:56 AM"}
{"TimeStamp":"2018-12-20T11:30:15.4033069+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 11:30:15 AM"}
{"TimeStamp":"2018-12-20T11:30:19.1763565+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 11:30:19 AM"}
{"TimeStamp":"2018-12-20T11:30:31.4447843+01:00","MessageType":"CLIENT_PULSE","Message":"74D9C28E-E2DA-4108-9388-C8521E235ECC:::1:3_2_0","Date":"18/12/20 11:30:31 AM"}
{"TimeStamp":"2018-12-20T11:32:32.2142967+01:00","MessageType":"INFO","Message":"Sync Compliance Notification Successfully Executed","Date":"18/12/20 11:32:32 AM"}
{"TimeStamp":"2018-12-20T11:32:50.2893374+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 11:32:50 AM"}
{"TimeStamp":"2018-12-20T11:32:53.3093362+01:00","MessageType":"CLIENT_PULSE","Message":"74D9C28E-E2DA-4108-9388-C8521E235ECC:::1:3_2_0","Date":"18/12/20 11:32:53 AM"}
{"TimeStamp":"2018-12-20T11:32:57.442486+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 11:32:57 AM"}
{"TimeStamp":"2018-12-20T11:34:57.186254+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 11:34:57 AM"}
{"TimeStamp":"2018-12-20T11:35:00.5725447+01:00","MessageType":"CLIENT_PULSE","Message":"74D9C28E-E2DA-4108-9388-C8521E235ECC:::1:3_2_0","Date":"18/12/20 11:35:00 AM"}
{"TimeStamp":"2018-12-20T11:36:09.715294+01:00","MessageType":"ERROR>>EntityFramework","Message":"[System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.\r\n   at System.Data.Entity.Internal.InternalContext.SaveChanges()\r\n   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()\r\n   at System.Data.Entity.DbContext.SaveChanges()\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.ClientPushAppointmentData(IntegrationAppointmentDataIngressPayLoad integrationAppointmentDataIngressPayLoad) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 234]Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.","Date":"18/12/20 11:36:09 AM"}
{"TimeStamp":"2018-12-20T11:36:16.9996971+01:00","MessageType":"ERROR>>EntityFramework","Message":"[System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.\r\n   at System.Data.Entity.Internal.InternalContext.SaveChanges()\r\n   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()\r\n   at System.Data.Entity.DbContext.SaveChanges()\r\n   at PatientDataAdministration.Web.Areas.ClientCommunication.Controllers.SyncController.ClientPushAppointmentData(IntegrationAppointmentDataIngressPayLoad integrationAppointmentDataIngressPayLoad) in C:\\Users\\Arigbede Moses\\Documents\\Visual Studio 2017\\Projects\\pda\\PatientDataAdministration.Web\\Areas\\ClientCommunication\\Controllers\\SyncController.cs:line 234]Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.","Date":"18/12/20 11:36:16 AM"}
{"TimeStamp":"2018-12-20T11:36:17.3736994+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 11:36:17 AM"}
{"TimeStamp":"2018-12-20T14:53:21.0474303+01:00","MessageType":"INFO","Message":"Started Cron Manager","Date":"18/12/20 02:53:21 PM"}
{"TimeStamp":"2018-12-20T14:53:23.7206915+01:00","MessageType":"INFO","Message":"Started Recurrent Data Manager","Date":"18/12/20 02:53:23 PM"}
{"TimeStamp":"2018-12-20T15:28:03.8019197+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 03:28:03 PM"}
{"TimeStamp":"2018-12-20T16:12:14.1939871+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:12:14 PM"}
{"TimeStamp":"2018-12-20T16:12:19.1881203+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:12:19 PM"}
{"TimeStamp":"2018-12-20T16:12:24.1891837+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:12:24 PM"}
{"TimeStamp":"2018-12-20T16:12:38.0974403+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:12:38 PM"}
{"TimeStamp":"2018-12-20T16:12:45.248584+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:12:45 PM"}
{"TimeStamp":"2018-12-20T16:17:51.3988899+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:17:51 PM"}
{"TimeStamp":"2018-12-20T16:18:07.8664437+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:18:07 PM"}
{"TimeStamp":"2018-12-20T16:18:26.5066037+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:18:26 PM"}
{"TimeStamp":"2018-12-20T16:19:34.5966948+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:19:34 PM"}
{"TimeStamp":"2018-12-20T16:23:23.5158874+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:23 PM"}
{"TimeStamp":"2018-12-20T16:23:24.2054121+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:24 PM"}
{"TimeStamp":"2018-12-20T16:23:29.1809789+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:29 PM"}
{"TimeStamp":"2018-12-20T16:23:34.182025+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:34 PM"}
{"TimeStamp":"2018-12-20T16:23:39.1801309+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:39 PM"}
{"TimeStamp":"2018-12-20T16:23:44.1977017+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:44 PM"}
{"TimeStamp":"2018-12-20T16:23:49.2066995+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:49 PM"}
{"TimeStamp":"2018-12-20T16:23:54.1977016+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:23:54 PM"}
{"TimeStamp":"2018-12-20T16:24:05.4917657+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:05 PM"}
{"TimeStamp":"2018-12-20T16:24:09.2692905+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:09 PM"}
{"TimeStamp":"2018-12-20T16:24:14.1883522+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:14 PM"}
{"TimeStamp":"2018-12-20T16:24:19.2084085+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:19 PM"}
{"TimeStamp":"2018-12-20T16:24:24.1904084+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:24 PM"}
{"TimeStamp":"2018-12-20T16:24:41.3347209+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:24:41 PM"}
{"TimeStamp":"2018-12-20T16:25:04.1264434+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:25:04 PM"}
{"TimeStamp":"2018-12-20T16:25:04.4394416+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:25:04 PM"}
{"TimeStamp":"2018-12-20T16:26:42.0057783+01:00","MessageType":"CLIENT_PULSE","Message":"7C4FF343-7EAD-4B56-B908-BCD4C00E7648:::1:3_2_0","Date":"18/12/20 04:26:42 PM"}
{"TimeStamp":"2018-12-20T17:53:03.782091+01:00","MessageType":"CLIENT_PULSE","Message":"FED7646A-0216-4B70-97F9-E50C183CD72C:::1:3_2_0","Date":"18/12/20 05:53:03 PM"}
